version: "3.9"

services:
  db:
    image: postgres:13
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - DB_HOST
      - DB_PORT
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend-service:
    build: ./backend
    env_file: .env
    environment:
      - WOOCOMMERCE_URL
      - CONSUMER_KEY
      - CONSUMER_SECRET
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  frontend-service:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-service

volumes:
  pgdata:
